name: CI

on:
  push:
    branches: [ v4 ]
  pull_request:
    branches: [ v4 ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.6

      - name: Pip Installer
        uses: BSFishy/pip-action@8f2d471d809dc20b6ada98c91910b6ae6243f318
        with:
          requirements:
            - $GITHUB_WORKSPACE/dsmrreader/provisioning/requirements/base.txt
            - $GITHUB_WORKSPACE/dsmrreader/provisioning/requirements/dev.txt

#      - name: Setup MySQL
#        uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
#        with:
#          mysql version:
#          mysql root password: # optional, default is
#          # MYSQL_DATABASE - name for the default database that is created
#          mysql database: test_dsmrreader
#          mysql user: # optional, default is
#          # MYSQL_PASSWORD - specified superuser password which user is power for created database
#          mysql password: # optional, default is

#      - name: Setup PostgreSQL
#        uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
#        with:
#          postgresql version: # optional, default is latest
#          postgresql db: test_dsmrreader
#          postgresql user: root
#          postgresql password: rootpw
