name: CI

on:
  push:
    branches: [ v4 ]
  pull_request:
    branches: [ v4 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.6
#          - 3.7
#          - 3.8

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ls -l /opt/hostedtoolcache/Python/

#      - name: Cache
#        uses: actions/cache@v2.1.2
#        with:
#          path: /var/tmp/pip-cache/
#          key: ${{ runner.os }}-${{ hashFiles('/home/runner/work/dsmr-reader/dsmr-reader/dsmrreader/provisioning/requirements/base.txt') }}-${{ hashFiles('/home/runner/work/dsmr-reader/dsmr-reader/dsmrreader/provisioning/requirements/dev.txt') }}

#      - name: Run a multi-line script
#        run: |
#          easy install pip
#          echo test, and deploy your project.

#      - name: Pip Installer
#        uses: BSFishy/pip-action@8f2d471d809dc20b6ada98c91910b6ae6243f318
#        with:
#          requirements: /home/runner/work/dsmr-reader/dsmr-reader/dsmrreader/provisioning/requirements/dev.txt
#          extra: --cache-dir /var/tmp/pip-cache/

#      - name: Setup MySQL
#        uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
#        with:
#          mysql version:
#          mysql root password: # optional, default is
#          # MYSQL_DATABASE - name for the default database that is created
#          mysql database: test_dsmrreader
#          mysql user: # optional, default is
#          # MYSQL_PASSWORD - specified superuser password which user is power for created database
#          mysql password: # optional, default is

#      - name: Setup PostgreSQL
#        uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
#        with:
#          postgresql version: # optional, default is latest
#          postgresql db: test_dsmrreader
#          postgresql user: root
#          postgresql password: rootpw
